{
 "PRed":[
  {
   "PR":{
    "__lazy_json__":"pr_json/494096267.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"1.4.1"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad":false,
 "conda-forge.yml":{
  "provider":{
   "linux":"azure",
   "osx":"azure",
   "win":"azure"
  }
 },
 "feedstock_name":"nest-asyncio",
 "hash_type":"sha256",
 "linux_64_meta_yaml":{
  "about":{
   "description":"By design asyncio does not allow its event loop to be nested.\nThis presents a practical problem - when in an environment where the event loop is already running it's impossible to run tasks and wait for the result.\nTrying to do so will give the error RuntimeError - This event loop is already running.\nThe issue pops up in various environments, such as web servers, GUI applications and in Jupyter notebooks.\nThis module patches asyncio to allow nested use of asyncio.run and loop.run_until_complete.\n",
   "dev_url":"https://github.com/erdewit/nest_asyncio",
   "doc_url":"https://github.com/erdewit/nest_asyncio",
   "home":"https://github.com/erdewit/nest_asyncio",
   "license":"BSD-2-Clause",
   "license_family":"BSD",
   "license_file":"LICENSE",
   "summary":"Patch asyncio to allow nested event loops"
  },
  "build":{
   "noarch":"python",
   "number":"0",
   "script":"-m pip install . -vv"
  },
  "extra":{
   "recipe-maintainers":[
    "yehoshuadimarsky"
   ]
  },
  "package":{
   "name":"nest-asyncio",
   "version":"1.4.1"
  },
  "requirements":{
   "host":[
    "python >=3.5",
    "pip",
    "setuptools"
   ],
   "run":[
    "python >=3.5"
   ]
  },
  "source":{
   "sha256":"b86c3193abda5b2eeccf8c79894bc71c680369a178f4b068514ac00720b14e01",
   "url":"https://pypi.io/packages/source/n/nest_asyncio/nest_asyncio-1.4.1.tar.gz"
  },
  "test":{
   "imports":[
    "nest_asyncio"
   ]
  }
 },
 "linux_64_requirements":{
  "build":{
   "__set__":true,
   "elements":[]
  },
  "host":{
   "__set__":true,
   "elements":[
    "pip",
    "python",
    "setuptools"
   ]
  },
  "run":{
   "__set__":true,
   "elements":[
    "python"
   ]
  },
  "test":{
   "__set__":true,
   "elements":[]
  }
 },
 "meta_yaml":{
  "about":{
   "description":"By design asyncio does not allow its event loop to be nested.\nThis presents a practical problem - when in an environment where the event loop is already running it's impossible to run tasks and wait for the result.\nTrying to do so will give the error RuntimeError - This event loop is already running.\nThe issue pops up in various environments, such as web servers, GUI applications and in Jupyter notebooks.\nThis module patches asyncio to allow nested use of asyncio.run and loop.run_until_complete.\n",
   "dev_url":"https://github.com/erdewit/nest_asyncio",
   "doc_url":"https://github.com/erdewit/nest_asyncio",
   "home":"https://github.com/erdewit/nest_asyncio",
   "license":"BSD-2-Clause",
   "license_family":"BSD",
   "license_file":"LICENSE",
   "summary":"Patch asyncio to allow nested event loops"
  },
  "build":{
   "noarch":"python",
   "number":"0",
   "script":"-m pip install . -vv"
  },
  "extra":{
   "recipe-maintainers":[
    "yehoshuadimarsky",
    "yehoshuadimarsky",
    "yehoshuadimarsky"
   ]
  },
  "package":{
   "name":"nest-asyncio",
   "version":"1.4.1"
  },
  "requirements":{
   "host":[
    "python >=3.5",
    "pip",
    "setuptools",
    "python >=3.5",
    "pip",
    "setuptools",
    "python >=3.5",
    "pip",
    "setuptools"
   ],
   "run":[
    "python >=3.5",
    "python >=3.5",
    "python >=3.5"
   ]
  },
  "source":{
   "sha256":"b86c3193abda5b2eeccf8c79894bc71c680369a178f4b068514ac00720b14e01",
   "url":"https://pypi.io/packages/source/n/nest_asyncio/nest_asyncio-1.4.1.tar.gz"
  },
  "test":{
   "imports":[
    "nest_asyncio",
    "nest_asyncio",
    "nest_asyncio"
   ]
  }
 },
 "name":"nest-asyncio",
 "new_version":"1.4.3",
 "new_version_attempts":{
  "1.4.1":1,
  "1.4.2":159,
  "1.4.3":248
 },
 "new_version_errors":{
  "1.4.3":"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '1.4.3' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ nameUnderscore[0] }}/{{ nameUnderscore }}/{{ nameUnderscore }}-{{ version }}.tar.gz'\n"
 },
 "osx_64_meta_yaml":{
  "about":{
   "description":"By design asyncio does not allow its event loop to be nested.\nThis presents a practical problem - when in an environment where the event loop is already running it's impossible to run tasks and wait for the result.\nTrying to do so will give the error RuntimeError - This event loop is already running.\nThe issue pops up in various environments, such as web servers, GUI applications and in Jupyter notebooks.\nThis module patches asyncio to allow nested use of asyncio.run and loop.run_until_complete.\n",
   "dev_url":"https://github.com/erdewit/nest_asyncio",
   "doc_url":"https://github.com/erdewit/nest_asyncio",
   "home":"https://github.com/erdewit/nest_asyncio",
   "license":"BSD-2-Clause",
   "license_family":"BSD",
   "license_file":"LICENSE",
   "summary":"Patch asyncio to allow nested event loops"
  },
  "build":{
   "noarch":"python",
   "number":"0",
   "script":"-m pip install . -vv"
  },
  "extra":{
   "recipe-maintainers":[
    "yehoshuadimarsky"
   ]
  },
  "package":{
   "name":"nest-asyncio",
   "version":"1.4.1"
  },
  "requirements":{
   "host":[
    "python >=3.5",
    "pip",
    "setuptools"
   ],
   "run":[
    "python >=3.5"
   ]
  },
  "source":{
   "sha256":"b86c3193abda5b2eeccf8c79894bc71c680369a178f4b068514ac00720b14e01",
   "url":"https://pypi.io/packages/source/n/nest_asyncio/nest_asyncio-1.4.1.tar.gz"
  },
  "test":{
   "imports":[
    "nest_asyncio"
   ]
  }
 },
 "osx_64_requirements":{
  "build":{
   "__set__":true,
   "elements":[]
  },
  "host":{
   "__set__":true,
   "elements":[
    "pip",
    "python",
    "setuptools"
   ]
  },
  "run":{
   "__set__":true,
   "elements":[
    "python"
   ]
  },
  "test":{
   "__set__":true,
   "elements":[]
  }
 },
 "pinning_version":"2020.09.28.09.54.05",
 "raw_meta_yaml":"{% set name = \"nest-asyncio\" %}\n{% set nameUnderscore = \"nest_asyncio\" %}\n{% set version = \"1.4.1\" %}\n\npackage:\n  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/{{ nameUnderscore[0] }}/{{ nameUnderscore }}/{{ nameUnderscore }}-{{ version }}.tar.gz\n  sha256: b86c3193abda5b2eeccf8c79894bc71c680369a178f4b068514ac00720b14e01\n\nbuild:\n  noarch: python\n  number: 0\n  script: {{ PYTHON }} -m pip install . -vv\n\nrequirements:\n  host:\n    - python >=3.5\n    - pip\n    - setuptools\n  run:\n    - python >=3.5\n\ntest:\n  imports:\n    - nest_asyncio\n\nabout:\n  home: https://github.com/erdewit/nest_asyncio\n  license: BSD-2-Clause\n  license_family: BSD\n  license_file: LICENSE\n  summary: Patch asyncio to allow nested event loops\n  description: |\n    By design asyncio does not allow its event loop to be nested. \n    This presents a practical problem - when in an environment where the event loop is already running it's impossible to run tasks and wait for the result. \n    Trying to do so will give the error RuntimeError - This event loop is already running.\n    The issue pops up in various environments, such as web servers, GUI applications and in Jupyter notebooks.\n    This module patches asyncio to allow nested use of asyncio.run and loop.run_until_complete.\n  doc_url: https://github.com/erdewit/nest_asyncio\n  dev_url: https://github.com/erdewit/nest_asyncio\n\nextra:\n  recipe-maintainers:\n    - yehoshuadimarsky\n",
 "req":{
  "__set__":true,
  "elements":[
   "pip",
   "python",
   "setuptools"
  ]
 },
 "requirements":{
  "build":{
   "__set__":true,
   "elements":[]
  },
  "host":{
   "__set__":true,
   "elements":[
    "pip",
    "python",
    "setuptools"
   ]
  },
  "run":{
   "__set__":true,
   "elements":[
    "python"
   ]
  },
  "test":{
   "__set__":true,
   "elements":[]
  }
 },
 "smithy_version":"No azure token. Create a token and\nput it in ~/.conda-smithy/azure.token\n3.7.10",
 "strong_exports":false,
 "total_requirements":{
  "build":{
   "__set__":true,
   "elements":[]
  },
  "host":{
   "__set__":true,
   "elements":[
    "pip",
    "python >=3.5",
    "setuptools"
   ]
  },
  "run":{
   "__set__":true,
   "elements":[
    "python >=3.5"
   ]
  },
  "test":{
   "__set__":true,
   "elements":[]
  }
 },
 "url":"https://pypi.io/packages/source/n/nest_asyncio/nest_asyncio-1.4.0.tar.gz",
 "version":"1.4.1",
 "win_64_meta_yaml":{
  "about":{
   "description":"By design asyncio does not allow its event loop to be nested.\nThis presents a practical problem - when in an environment where the event loop is already running it's impossible to run tasks and wait for the result.\nTrying to do so will give the error RuntimeError - This event loop is already running.\nThe issue pops up in various environments, such as web servers, GUI applications and in Jupyter notebooks.\nThis module patches asyncio to allow nested use of asyncio.run and loop.run_until_complete.\n",
   "dev_url":"https://github.com/erdewit/nest_asyncio",
   "doc_url":"https://github.com/erdewit/nest_asyncio",
   "home":"https://github.com/erdewit/nest_asyncio",
   "license":"BSD-2-Clause",
   "license_family":"BSD",
   "license_file":"LICENSE",
   "summary":"Patch asyncio to allow nested event loops"
  },
  "build":{
   "noarch":"python",
   "number":"0",
   "script":"-m pip install . -vv"
  },
  "extra":{
   "recipe-maintainers":[
    "yehoshuadimarsky"
   ]
  },
  "package":{
   "name":"nest-asyncio",
   "version":"1.4.1"
  },
  "requirements":{
   "host":[
    "python >=3.5",
    "pip",
    "setuptools"
   ],
   "run":[
    "python >=3.5"
   ]
  },
  "source":{
   "sha256":"b86c3193abda5b2eeccf8c79894bc71c680369a178f4b068514ac00720b14e01",
   "url":"https://pypi.io/packages/source/n/nest_asyncio/nest_asyncio-1.4.1.tar.gz"
  },
  "test":{
   "imports":[
    "nest_asyncio"
   ]
  }
 },
 "win_64_requirements":{
  "build":{
   "__set__":true,
   "elements":[]
  },
  "host":{
   "__set__":true,
   "elements":[
    "pip",
    "python",
    "setuptools"
   ]
  },
  "run":{
   "__set__":true,
   "elements":[
    "python"
   ]
  },
  "test":{
   "__set__":true,
   "elements":[]
  }
 }
}